export const INITIAL_FORM_STATE = { 
    name: '', 
    leads_table: 'leads', 
    description: '', 
    delay_seconds: 30, 
    response_delay_seconds: 0,
    split_response_enabled: true,
    window_close_label: [],
    agent_id: '', 
    secondary_agent_ids: [],
    blocked_messages: [], 
    allowed_contacts: [], 
    zapvoice_url: '', 
    zapvoice_api_token: '', 
    zapvoice_client_id: '', 
    labels_on_message: [], 
    delete_keywords: [], 
    delete_message: '', 
    followup_enabled: false, 
    followup_steps: [], 
    followup_business_hours: { enabled: false, start: '08:00', end: '18:00', weekdays: true, saturday: false, sunday: false }, 
    followup_cancel_label: '',
    followup_required_label: '',
    followup_add_label: '',
    followup_on_reply: 'stop',
    process_audio: true,
    process_image: true,
    memory_sync_enabled: false, 
    memory_phone_path: 'phone', 
    memory_name_path: '', 
    memory_mappings: [], 
    token: '', 
    memory_token: '',
    ignore_by_label: '',
    handoff_labels_to_add: [],
    handoff_labels_to_remove: [],
    handoff_keyword: '',
    handoff_message: '',
    ai_handoff_labels_to_add: [],
    ai_handoff_labels_to_remove: [],
    ai_handoff_keyword: '',
    ai_handoff_message: ''
};

export const EDIT_TABS = [
    { id: 'geral', label: 'Geral', icon: '⚙️' },
    { id: 'filtros', label: 'Filtros', icon: '🔍' },
    { id: 'zapvoice', label: 'ZapVoice', icon: '💬' },
    { id: 'memoria', label: 'Memória', icon: '🧠' },
    { id: 'handoff', label: 'Handoff', icon: '🤝' },
    { id: 'delecao', label: 'Deleção', icon: '🗑️' }
];
